name: Azure Static Web Apps CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["main"]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Install ROOT deps for Next.js app
      - name: Install app dependencies
        run: npm ci || npm install

      # Build Next.js (next.config.js has output:'export' -> /out)
      - name: Build App
        run: npm run build

      # Deploy app + API (SWA builds API; we force registry + set language)
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_MEADOW_0B2D2151E2 || secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"
          output_location: "out"
          api_location: "api"
          api_language: "node"  # <— tell SWA it's a Node Functions API
          api_build_command: "npm install --omit=dev --registry=https://registry.npmjs.org/"
          skip_api_build: false

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_MEADOW_0B2D2151E2 || secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close
