name: Azure Static Web Apps CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["main"]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # NOTE: the token name may be long and include your env name.
          # If this short name doesn't exist, open Repo Settings → Secrets → Actions
          # and use the exact secret name you see there.
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"

          # Paths for our project
          app_location: "/"      # root (Next.js app)
          api_location: "api"    # Azure Functions folder
          output_location: "out" # Next static export output

          # Build command (Next builds to /out because next.config.js has output:'export')
          app_build_command: "npm run build"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
