name: Azure Static Web Apps CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["main"]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- Build API ourselves and force npmjs registry ---
      - name: Install API dependencies (force npmjs.org)
        working-directory: api
        run: npm install --omit=dev --registry=https://registry.npmjs.org/

      # --- Build the Next.js app (static export via next.config.js output:'export') ---
      - name: Build App
        run: npm run build

      # --- Deploy both app and API (skip API build because we already did it) ---
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_MEADOW_0B2D2151E2 || secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"
          output_location: "out"
          api_location: "api"
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_MEADOW_0B2D2151E2 || secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close
